import { useState, type ReactNode } from 'react'
import MeetingTimeline from '../MeetingTimeline'
import { mentraOnboardingPrototype } from '../../data/projectExperiences'

function Shell({ name, children, actions }: { name: string; children: ReactNode; actions?: ReactNode }) {
  return <div className="prototype-app"><header><strong>{name}</strong>{actions}</header>{children}</div>
}
function Mentra() {
  const [open, setOpen] = useState(false), [loaded, setLoaded] = useState(false)
  return <Shell name="Mentra · onboarding" actions={<a href={mentraOnboardingPrototype} target="_blank" rel="noopener noreferrer">Open in Figma ↗</a>}>
    {open ? <div className="prototype-embed"><p role="status">{loaded ? 'Use the prototype below. If Figma requires access, open it in a new tab.' : 'Loading Figma…'}</p><iframe title="Original Mentra onboarding Figma prototype" src={`https://www.figma.com/embed?embed_host=share&url=${encodeURIComponent(mentraOnboardingPrototype)}`} onLoad={() => setLoaded(true)} allowFullScreen /></div> : <div className="prototype-original"><video controls preload="metadata" poster="/Assets/Projects/mentra-brand/motion/mentra-onboarding-prototype-poster.jpg" aria-label="Recorded original Mentra onboarding prototype"><source src="/Assets/Projects/mentra-brand/motion/mentra-onboarding-prototype.mp4" type="video/mp4" /></video><button className="prototype-primary" onClick={() => setOpen(true)}>Load interactive Figma prototype</button><p>Original onboarding flow. The recording is available while the Figma prototype is closed.</p></div>}
  </Shell>
}
function MiniApps() {
  const [selected, setSelected] = useState('Notes'), [step, setStep] = useState<'browse' | 'permissions' | 'running'>('browse'), [allowed, setAllowed] = useState(false), [note, setNote] = useState(''), [notes, setNotes] = useState<string[]>([])
  const apps = [{ name: 'Notes', permission: 'Microphone', image: 'notes.png' }, { name: 'Conversations', permission: 'Microphone', image: 'conversations.png' }, { name: 'Live Transcript', permission: 'Microphone', image: 'live-transcript.png' }, { name: 'Meet', permission: 'Camera and microphone', image: 'meet-home.png' }, { name: 'Guidance', permission: 'Location', image: 'guidance.png' }]
  const app = apps.find(item => item.name === selected)!
  return <Shell name="Mentra MiniApps" actions={<button onClick={() => { setStep('browse'); setAllowed(false) }}>Back to apps</button>}><div className="prototype-split">
    <section>{step === 'browse' ? <><h2>What would you like to do?</h2><div className="prototype-app-list">{apps.map(item => <button key={item.name} onClick={() => { setSelected(item.name); setAllowed(false); setStep('permissions') }}><strong>{item.name}</strong><span>Open app →</span></button>)}</div></> : step === 'permissions' ? <><h2>{selected}</h2><p>Review the requested permission before launching.</p><label className="prototype-check"><input type="checkbox" checked={allowed} onChange={event => setAllowed(event.target.checked)} />{app.permission}</label><p className="prototype-caption">This browser adaptation requests no device permission.</p><button className="prototype-primary" disabled={!allowed} onClick={() => setStep('running')}>Launch {selected}</button></> : <><p className="prototype-kicker">Running on the sample glasses display</p><h2>{selected}</h2><div className="prototype-glasses" role="status">{selected === 'Guidance' ? 'Next turn · continue straight to the station' : selected === 'Meet' ? 'Ready to join · sample meeting' : selected === 'Live Transcript' ? '“Let’s review the next step together.”' : selected === 'Conversations' ? 'Today · sample conversation ready to review' : notes[notes.length - 1] || 'Your next note appears here'}</div>{selected === 'Notes' && <form onSubmit={event => { event.preventDefault(); if(note.trim()){setNotes(old => [...old, note.trim()]);setNote('')} }}><label>Add a note<input value={note} onChange={event => setNote(event.target.value)} /></label><button disabled={!note.trim()}>Save note</button><ul>{notes.map((item, index) => <li key={index}>{item}</li>)}</ul></form>}</> }</section>
    <figure><img src={`/Assets/Projects/mentra-miniapps/figma/${app.image}`} alt={`Original ${selected} MiniApp screen`} /><figcaption>Original design screen</figcaption></figure>
  </div></Shell>
}
function Clawed() {
  const [draft, setDraft] = useState('Thanks for the update. I’ll review the document this afternoon.'), [state, setState] = useState<'draft' | 'approved' | 'dismissed'>('draft'), [tab, setTab] = useState('Approvals')
  return <Shell name="Clawed" actions={<button onClick={() => {setState('draft');setTab('Approvals');setDraft('Thanks for the update. I’ll review the document this afternoon.')}}>Reset demo</button>}><nav className="prototype-tabs" aria-label="Assistant views">{['Approvals','Receipts'].map(item => <button key={item} aria-pressed={tab===item} onClick={() => setTab(item)}>{item}</button>)}</nav><section className="prototype-content">
    {tab === 'Approvals' ? <><p className="prototype-kicker">Sample inbox · review before acting</p><h2>A draft needs your approval</h2><p>Destination: sample teammate · channel: email</p><label>Draft reply<textarea value={draft} disabled={state!=='draft'} onChange={event => setDraft(event.target.value)} /></label><div className="prototype-actions"><button className="prototype-primary" disabled={state!=='draft'||!draft.trim()} onClick={() => {setState('approved');setTab('Receipts')}}>Approve draft</button><button disabled={state!=='draft'} onClick={() => setState('dismissed')}>Dismiss</button></div><p role="status">{state === 'dismissed' ? 'Draft dismissed. No action was taken.' : state === 'approved' ? 'Approved in this demo.' : 'Nothing is sent from this prototype.'}</p></> : <><h2>Action receipts</h2>{state==='approved' ? <article className="prototype-receipt"><dl><div><dt>Request</dt><dd>Reply to the sample update</dd></div><div><dt>Approval</dt><dd>Approved by you in this session</dd></div><div><dt>Draft</dt><dd>{draft}</dd></div><div><dt>Result</dt><dd>Simulated completion. No message sent.</dd></div></dl></article> : <p>No approved actions yet. Review the draft in Approvals.</p>}</>}
  </section></Shell>
}
function Organization() {
  const [tab, setTab] = useState('Knowledge'), [query, setQuery] = useState(''), [review, setReview] = useState<'pending'|'approved'|'rejected'>('pending')
  const records = [{ title:'Projects', text:'Demo project · launch checklist · owner: product team' }, {title:'Team',text:'Demo team · design, product and engineering roles'}, {title:'SOPs',text:'Demo procedure · review external changes before approval'}]
  return <Shell name="OrgDashboard" actions={<button onClick={() => {setReview('pending');setQuery('');setTab('Knowledge')}}>Reset demo</button>}><nav className="prototype-tabs" aria-label="Workspace views">{['Knowledge','Sources','Action queue'].map(item => <button key={item} aria-pressed={tab===item} onClick={() => setTab(item)}>{item}</button>)}</nav><section className="prototype-content">
    {tab==='Knowledge' ? <><h2>Shared organization context</h2><label>Search knowledge<input value={query} onChange={event => setQuery(event.target.value)} type="search" /></label>{records.filter(item => `${item.title} ${item.text}`.toLowerCase().includes(query.toLowerCase())).map(item => <details key={item.title}><summary>{item.title}</summary><p>{item.text}</p><small>Source: sample workspace record</small></details>)}{!records.some(item => `${item.title} ${item.text}`.toLowerCase().includes(query.toLowerCase()))&&<p role="status">No matching records. Try “team” or “projects”.</p>}</> : tab==='Sources' ? <><h2>Connected sources</h2><ul className="prototype-source-list"><li>Sample GitHub workspace · read only</li><li>Sample project tracker · read only</li><li>Sample team directory · read only</li></ul><p>No external account is connected in this prototype.</p></> : <><h2>Review a proposed action</h2><p>Proposal: update the demo launch checklist from the reviewed project record.</p><details><summary>Inspect supporting context</summary><p>Demo project → launch checklist. The proposed change adds a human review step before publication.</p></details><div className="prototype-actions"><button className="prototype-primary" disabled={review!=='pending'} onClick={() => setReview('approved')}>Approve change</button><button disabled={review!=='pending'} onClick={() => setReview('rejected')}>Reject change</button></div><p role="status">{review==='pending'?'Awaiting your review.':review==='approved'?'Approved in the demo. No external system changed.':'Rejected. The sample record stays unchanged.'}</p></>}
  </section></Shell>
}
function Planner() {
  const [capacity, setCapacity] = useState('Full'), [applied, setApplied] = useState(false), [done, setDone] = useState<string[]>([])
  const tasks = applied && capacity==='Lighter' ? ['Review the brief','Lunch break','Short walk','Admin tasks'] : ['Deep work on the brief','Review the brief','Lunch break','Short walk','Admin tasks']
  return <Shell name="Health App · today" actions={<button onClick={()=>{setCapacity('Full');setApplied(false);setDone([])}}>Reset plan</button>}><div className="prototype-split"><section><p className="prototype-kicker">Sample day</p><h2>Plan around your capacity</h2><label>Today’s capacity<select value={capacity} onChange={event => {setCapacity(event.target.value);setApplied(false)}}><option>Full</option><option>Lighter</option></select></label><p>{capacity==='Lighter'?'Proposal: move deep work to another day and keep breaks in today’s plan.':'Proposal: keep the full task list with breaks protected.'}</p><button className="prototype-primary" onClick={()=>setApplied(true)}>Apply proposed plan</button><p role="status">{applied?'Your choice is applied to the sample schedule.':'Review the proposal before changing your schedule.'}</p></section><section><h2>Today’s plan</h2><ul className="prototype-task-list">{tasks.map(task => <li key={task}><label><input type="checkbox" checked={done.includes(task)} onChange={event => setDone(old => event.target.checked?[...old,task]:old.filter(item=>item!==task))}/><span>{task}</span></label></li>)}</ul><p>{tasks.filter(task => done.includes(task)).length} tasks checked</p></section></div></Shell>
}
function Parking() {
  const [step, setStep] = useState<'select'|'review'|'confirmed'>('select'), [selected, setSelected] = useState<number|null>(null)
  return <Shell name="VJ Parivar · vehicle parking" actions={<button onClick={()=>{setStep('select');setSelected(null)}}>Start again</button>}><section className="prototype-content prototype-parking">
    <p className="prototype-kicker">Sample parking layout</p><h2>{step==='select'?'Choose your parking space':step==='review'?'Review your selection':'Selection confirmed in the demo'}</h2>
    {step==='select'?<><p>Select an available space to inspect it. Hatched spaces are unavailable.</p><div className="prototype-parking-map" role="group" aria-label="Parking spaces">{Array.from({length:12},(_,index)=>index+1).map(spot=><button key={spot} disabled={[3,7,10].includes(spot)} aria-pressed={selected===spot} onClick={()=>setSelected(spot)}>{String(spot).padStart(2,'0')}</button>)}</div>{selected!==null&&<p role="status">Space {String(selected).padStart(2,'0')} · sample four-wheeler bay · 2.5 × 5 m</p>}<button className="prototype-primary" disabled={selected===null} onClick={()=>setStep('review')}>Review booking</button></>:<><dl><div><dt>Space</dt><dd>{String(selected).padStart(2,'0')}</dd></div><div><dt>Vehicle type</dt><dd>Four-wheeler</dd></div><div><dt>Dimensions</dt><dd>2.5 × 5 m · illustrative</dd></div></dl>{step==='review'?<div className="prototype-actions"><button className="prototype-primary" onClick={()=>setStep('confirmed')}>Confirm sample booking</button><button onClick={()=>setStep('select')}>Change space</button></div>:<p role="status">Your sample selection is saved for this session. No real space was booked.</p>}</>}
    <details><summary>View original parking design</summary><img src="/Assets/Projects/vj/photos/car-parking.png" alt="Original VJ Parivar vehicle parking screen" /></details>
  </section></Shell>
}
function Builder() {
  const [blocks, setBlocks] = useState<string[]>(['Heading','Text']), [padding, setPadding] = useState(24), [tab, setTab] = useState('Output')
  const code=`<main style="padding: ${padding}px">\n${blocks.map(block=>block==='Heading'?'  <h1>Your first page</h1>':block==='Text'?'  <p>Built with blocks.</p>':'  <button>Continue</button>').join('\n')}\n</main>`
  return <Shell name="Code for Build" actions={<button onClick={()=>{setBlocks(['Heading','Text']);setPadding(24);setTab('Output')}}>Reset lesson</button>}><div className="prototype-split"><section><h2>Build your first page</h2><p>Add a block, change the padding, then inspect the output and code.</p><div className="prototype-actions">{['Heading','Text','Button'].map(block=><button key={block} onClick={()=>setBlocks(old=>[...old,block])}>Add {block.toLowerCase()}</button>)}</div><label>Padding <output>{padding}px</output><input type="range" min="0" max="64" value={padding} onChange={event=>setPadding(Number(event.target.value))}/></label><ol className="prototype-block-list">{blocks.map((block,index)=><li key={index}><span>{block}</span><button aria-label={`Remove ${block.toLowerCase()} block ${index+1}`} onClick={()=>setBlocks(old=>old.filter((_,i)=>i!==index))}>Remove</button></li>)}</ol></section><section><nav className="prototype-tabs" aria-label="Lesson views">{['Output','Code'].map(item=><button key={item} aria-pressed={tab===item} onClick={()=>setTab(item)}>{item}</button>)}</nav>{tab==='Code'?<pre aria-label="Generated HTML">{code}</pre>:<iframe title="Your generated page" sandbox="" srcDoc={`<!doctype html><html><head><style>body{margin:0;font:16px system-ui;color:#242a24;background:#faf8f3}button{padding:12px 20px}</style></head><body>${code}</body></html>`}/>}</section></div></Shell>
}
function Editor() {
  const initial='export function Greeting() {\n  return <h1>Hello</h1>\n}'
  const [code,setCode]=useState(initial),[patch,setPatch]=useState(false),[status,setStatus]=useState('Ready to inspect the sample component.')
  return <Shell name="Ballah Code" actions={<button onClick={()=>{setCode(initial);setPatch(false);setStatus('Ready to inspect the sample component.')}}>Reset workspace</button>}><div className="prototype-editor"><section><h2>Greeting.tsx</h2><label>Component source<textarea spellCheck={false} value={code} onChange={event=>{setCode(event.target.value);setPatch(false)}}/></label></section><section><p className="prototype-kicker">Assistant · prepared example</p><h2>Review before applying</h2><p>Try the documented handoff: inspect a suggested change alongside the source.</p><button className="prototype-primary" onClick={()=>setPatch(true)}>Propose accessible label</button>{patch&&<><pre>+ aria-label="Greeting"</pre><button onClick={()=>{setCode(old=>old.includes('aria-label=')?old:old.replace('<h1','<h1 aria-label="Greeting"'));setPatch(false);setStatus('The label was applied to your local sample. No repository file changed.')}} disabled={!code.includes('<h1')}>Apply proposed change</button><button onClick={()=>{setPatch(false);setStatus('Suggestion dismissed. Your source is unchanged.')}}>Dismiss suggestion</button></>}<p role="status">{status}</p></section></div></Shell>
}
function Journey() {
  const [destination,setDestination]=useState('Station'),[step,setStep]=useState(0),[started,setStarted]=useState(false)
  const legs=['Walk to the sample bus stop','Take the sample bus to the interchange',`Continue to ${destination.toLowerCase()}`]
  return <Shell name="Raahi · journey planner" actions={<button onClick={()=>{setStarted(false);setStep(0)}}>Plan another journey</button>}><section className="prototype-content"><h2>{started?'Follow your journey':'Where would you like to go?'}</h2>{!started?<><label>Destination<select value={destination} onChange={event=>setDestination(event.target.value)}><option>Station</option><option>Home</option><option>Work</option></select></label><p>A prepared journey illustrates app-to-stop guidance. Routes and transport data are sample content.</p><button className="prototype-primary" onClick={()=>setStarted(true)}>Plan sample journey</button></>:<><ol className="prototype-journey">{legs.map((leg,index)=><li key={leg} aria-current={index===step?'step':undefined}>{leg}</li>)}</ol><p role="status">{step===3?'You’ve completed the sample journey.':`Leg ${step+1} of 3 · ${legs[step]}`}</p><button className="prototype-primary" disabled={step===3} onClick={()=>setStep(old=>old+1)}>{step===2?'Finish journey':'Complete this leg'}</button></>}</section></Shell>
}
export default function ProductPrototypes({ project }: { project: string }) {
  switch(project) {
    case 'mentra': return <Mentra />
    case 'mentra-miniapps': return <MiniApps />
    case 'executivelens': return <MeetingTimeline />
    case 'clawed-chat': return <Clawed />
    case 'org-dashboard': return <Organization />
    case 'healthapp': return <Planner />
    case 'vj-software': return <Parking />
    case 'code-for-build': return <Builder />
    case 'ballah-code': return <Editor />
    case 'raahi-project': return <Journey />
    default: return null
  }
}
